## NumPy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list) # This is numpy array
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
mat_arr = np.array(my_mat)
mat_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Some of the most common way to create an array 
print(np.arange(0, 11))
print(np.arange(0, 11, 2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [26]:
np.zeros([4,5]) # Pure zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones([2,3]) # All ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.linspace(0,5,8) # linearly placed numbers in range of 0 to 5 (all inclusive)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [39]:
np.eye(5) # To get an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.random.rand(4,2)

array([[0.57564965, 0.48029202],
       [0.87158308, 0.64249598],
       [0.58863825, 0.32055034],
       [0.10365563, 0.25941995]])

In [53]:
np.random.randn(3,3)

array([[ 0.66725244,  1.53525027, -0.08163739],
       [-0.50940946,  0.06832931,  0.00632242],
       [ 0.55793475,  0.52918096,  0.12371127]])

In [68]:
np.random.randint(1,100, 10)

array([22, 33, 33, 22,  1, 77,  6, 35, 40, 30])

In [69]:
arr = np.arange(25)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
randr = np.random.randint(0,50,10)

In [72]:
randr

array([ 4,  9,  0, 12, 12, 38, 31, 40, 11, 12])

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape()