## Learning Numpy

In [1]:
# Importing numpy
import numpy as np

In [2]:
ar = np.arange(15).reshape(3,5)
print(ar)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
# Shape of ndarray
ar.shape

(3, 5)

In [4]:
# No of axis
ar.ndim

2

In [5]:
# Type of data
ar.dtype.name

'int64'

In [6]:
# Item size of element of array
ar.itemsize

8

In [7]:
# Size of array (No of array)
ar.size

15

In [8]:
# Type of ndarray
type(ar)

numpy.ndarray

In [9]:
# Creating numpy array
new_arr = np.array([6,7,8])
print(new_arr)
type(new_arr)

[6 7 8]


numpy.ndarray

### No of ways to create a numpy array

In [10]:
a = np.array([1,2,3]) # 1d array (putting list in np.array() method)
print(a.dtype)
b = np.array([1.2, 2.3, 3.4])
print(b.dtype)

int64
float64


In [11]:
# Missing type of data
c = np.array([(1,2,3), (4.5, 5.6, 6.7)])
print(c)
print(c.dtype)

[[1.  2.  3. ]
 [4.5 5.6 6.7]]
float64


In [12]:
# Complex Number ndarray
d = np.array([[1,2], [3,4]], dtype=complex)
print(d)
print(d.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


In [13]:
"""
Creating array with zero's and one's
Use as an placeholder if size and shape is known, because expansion of array is an expensive operation
"""
e = np.zeros((3,4))
f = np.ones((2,3,4), dtype=np.int16)
g = np.empty((2,3)) # by default float type random data
print(f"Matrix of Zero's \n {e}")
print(f"Matrix of One's \n {f}")
print(f"Matix of Empty(float type) \n{g}")

Matrix of Zero's 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrix of One's 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
Matix of Empty(float type) 
[[1.  2.  3. ]
 [4.5 5.6 6.7]]


### Creating sequence using NumPy (1d array)

In [14]:
# Using arange function to create sequence
sq = np.arange(1, 10, 2)
print(sq)
print(type(sq)) # still ndarray

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [15]:
sq1 = np.arange(0,2,0.3)
print(sq1) # New sequenec

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [38]:
### Linespace will determine the step just provide the range and no of element required
from numpy import pi
# sq2 = np.linspace(0, 9, 10)
# print(sq2)

sq3 = np.linspace(0, 2*pi, 100)
sin_values = np.sin(sq3) # Many values evaluates the concept of it !!

### Printing Arrays

In [39]:
print(np.arange(0,10000))

[   0    1    2 ... 9997 9998 9999]


In [40]:
print(np.arange(0,10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
